### ISSUE TITLE
Does not post in group

### ISSUE THREAD

**Issue by SanjayVyas** [jheuel/pollrBot#2]
Of late, pollrbot is showing two issues
1. It can create a poll but when sharing in group, it does not pop up a list of polls
2. Sometimes when it posts the poll, it shows the number of votes but not voters names

**Comment by jheuel** [comment]
1) I could reproduce the issue and found that it was a problem with the Markdown parser that is used to format the poll messages. Messages are now formatted using HTML 445d8f5491dc8e6525035ac900d09b6ba2ee5ea4 and you should be able to post polls again.

2) There are a few situations in which the poll does not show the voter names:
   - If there are more than 100 voters (the polls gets really long and confusing)
   - If the message is to long with all voter names included (telegram limitation)

Thanks for reporting the issues! :-)
