### ISSUE TITLE
Name List of members

### ISSUE THREAD

**Issue by ChidChid** [jheuel/pollrBot#6]
I had use the pollrBot in Telegram that you built to create a poll in my group. It works good at first but when the voters exceeded 100, the name list (showing who voted for that choice) gone. 
![2](https://user-images.githubusercontent.com/55564109/65289032-b8d5f200-db7b-11e9-8f92-1ef68df42791.PNG)
How can I get back the name list under the choices as before 100 members?
![1](https://user-images.githubusercontent.com/55564109/65289060-d0ad7600-db7b-11e9-80c3-3ce14f2407bb.PNG)

Thank you.

**Comment by jheuel** [comment]
The problem is that when the message text gets too long telegram stops accepting it, at least that was the case when I last tried. I will investigate if something was changed.

**Comment by ChidChid** [comment]
That means i cant get the name list anymore?

**Comment by rizkyhidayat1234** [comment]
I get the same problem. Please can help me?

**Comment by jheuel** [comment]
I did just add a web view for polls that shows all names.
